### ISSUE TITLE
Learn PassportJS: authentication middleware in NodeJS which is better than JWT.

### ISSUE THREAD

**Issue by usrbinomarbash** [omarbelkady/NodeJS#12]

**Comment by manikarora8368** [comment]
you can use a library known as passport.js where you can set various authentication techniques .mentioning the link below of passport.js documentation- http://www.passportjs.org/packages/passport-google-oauth/

**Comment by usrbinomarbash** [comment]
thank you so much

**Comment by usrbinomarbash** [comment]
![OAuth_Big_Picture](https://user-images.githubusercontent.com/31806568/112837803-3c876d80-9094-11eb-961f-111743195bff.png)
